"""Pre-extracted triples for demo mode (no API key required)."""

DEMO_TRIPLES = [
    ("OpenAI", "FOUNDED_BY", "Sam Altman"),
    ("OpenAI", "FOUNDED_BY", "Elon Musk"),
    ("OpenAI", "FOUNDED_IN", "2015"),
    ("OpenAI", "HEADQUARTERED_IN", "San Francisco"),
    ("OpenAI", "DEVELOPED", "ChatGPT"),
    ("OpenAI", "DEVELOPED", "GPT-4"),
    ("Sam Altman", "CEO_OF", "OpenAI"),
    ("Elon Musk", "LEFT_BOARD", "OpenAI"),
    ("Elon Musk", "LEFT_BOARD_YEAR", "2018"),
    ("Elon Musk", "CEO_OF", "Tesla"),
    ("Elon Musk", "FOUNDED", "SpaceX"),
    ("Elon Musk", "ACQUIRED", "Twitter"),
    ("Tesla", "FOUNDED_BY", "Elon Musk"),
    ("Tesla", "FOUNDED_IN", "2003"),
    ("SpaceX", "FOUNDED_BY", "Elon Musk"),
    ("SpaceX", "FOUNDED_IN", "2002"),
    ("SpaceX", "HEADQUARTERED_IN", "Hawthorne"),
    ("Google", "FOUNDED_BY", "Larry Page"),
    ("Google", "FOUNDED_BY", "Sergey Brin"),
    ("Google", "FOUNDED_IN", "1998"),
    ("Google", "HEADQUARTERED_IN", "Mountain View"),
    ("Larry Page", "CREATED", "PageRank"),
    ("Sergey Brin", "CREATED", "PageRank"),
    ("Google", "ACQUIRED", "DeepMind"),
    ("Google", "ACQUISITION_YEAR", "2014"),
    ("DeepMind", "FOUNDED_BY", "Demis Hassabis"),
    ("DeepMind", "FOUNDED_BY", "Shane Legg"),
    ("DeepMind", "FOUNDED_BY", "Mustafa Suleyman"),
    ("DeepMind", "FOUNDED_IN", "2010"),
    ("DeepMind", "HEADQUARTERED_IN", "London"),
    ("Demis Hassabis", "CEO_OF", "DeepMind"),
    ("DeepMind", "DEVELOPED", "AlphaGo"),
    ("DeepMind", "DEVELOPED", "AlphaFold"),
    ("Sundar Pichai", "CEO_OF", "Google"),
    ("Sundar Pichai", "CEO_OF", "Alphabet"),
    ("Microsoft", "FOUNDED_BY", "Bill Gates"),
    ("Microsoft", "FOUNDED_BY", "Paul Allen"),
    ("Microsoft", "FOUNDED_IN", "1975"),
    ("Microsoft", "ACQUIRED", "GitHub"),
    ("Microsoft", "GITHUB_ACQUISITION_YEAR", "2018"),
    ("GitHub", "FOUNDED_IN", "2008"),
    ("Microsoft", "INVESTED_IN", "OpenAI"),
    ("Microsoft", "OPENAI_INVESTMENT", "10 billion USD"),
    ("Microsoft", "INTEGRATED", "GPT-4"),
    ("Satya Nadella", "CEO_OF", "Microsoft"),
    ("Apple", "FOUNDED_BY", "Steve Jobs"),
    ("Apple", "FOUNDED_BY", "Steve Wozniak"),
    ("Apple", "FOUNDED_IN", "1976"),
    ("Apple", "HEADQUARTERED_IN", "Cupertino"),
    ("Tim Cook", "CEO_OF", "Apple"),
    ("Tim Cook", "BECAME_CEO", "2011"),
    ("Steve Jobs", "STEPPED_DOWN", "2011"),
    ("Apple", "ACQUIRED", "Beats Electronics"),
    ("Meta", "FORMERLY_NAMED", "Facebook"),
    ("Meta", "FOUNDED_BY", "Mark Zuckerberg"),
    ("Meta", "FOUNDED_IN", "2004"),
    ("Meta", "FOUNDED_AT", "Harvard University"),
    ("Meta", "RENAMED", "2021"),
    ("Mark Zuckerberg", "CEO_OF", "Meta"),
    ("Meta", "ACQUIRED", "Instagram"),
    ("Instagram", "FOUNDED_IN", "2010"),
    ("Instagram", "FOUNDED_BY", "Kevin Systrom"),
    ("Meta", "ACQUIRED", "WhatsApp"),
    ("WhatsApp", "ACQUISITION_PRICE", "19 billion USD"),
    ("WhatsApp", "FOUNDED_IN", "2009"),
    ("Amazon", "FOUNDED_BY", "Jeff Bezos"),
    ("Amazon", "FOUNDED_IN", "1994"),
    ("Andy Jassy", "CEO_OF", "Amazon"),
    ("Jeff Bezos", "STEPPED_DOWN_CEO", "2021"),
    ("Amazon", "OWNS", "AWS"),
    ("Amazon", "ACQUIRED", "Twitch"),
    ("Twitch", "FOUNDED_IN", "2011"),
    ("NVIDIA", "FOUNDED_BY", "Jensen Huang"),
    ("NVIDIA", "FOUNDED_IN", "1993"),
    ("Jensen Huang", "CEO_OF", "NVIDIA"),
    ("IBM", "FOUNDED_IN", "1911"),
    ("IBM", "DEVELOPED", "Deep Blue"),
    ("Arvind Krishna", "CEO_OF", "IBM"),
    ("Oracle", "FOUNDED_BY", "Larry Ellison"),
    ("Oracle", "FOUNDED_IN", "1977"),
    ("Larry Ellison", "CTO_OF", "Oracle"),
    ("Oracle", "ACQUIRED", "Sun Microsystems"),
    ("Sun Microsystems", "CREATED", "Java"),
    ("Twitter", "FOUNDED_BY", "Jack Dorsey"),
    ("Twitter", "FOUNDED_IN", "2006"),
    ("Twitter", "RENAMED_TO", "X"),
    ("Twitter", "ACQUISITION_PRICE", "44 billion USD"),
    ("Elon Musk", "RENAMED", "X"),
    ("Linda Yaccarino", "CEO_OF", "X"),
    ("Netflix", "FOUNDED_BY", "Reed Hastings"),
    ("Netflix", "FOUNDED_IN", "1997"),
    ("Adobe", "FOUNDED_BY", "John Warnock"),
    ("Adobe", "CREATED", "PDF"),
    ("Adobe", "CREATED", "Photoshop"),
    ("Figma", "FOUNDED_BY", "Dylan Field"),
    ("Figma", "FOUNDED_IN", "2012"),
    ("Salesforce", "FOUNDED_BY", "Marc Benioff"),
    ("Salesforce", "FOUNDED_IN", "1999"),
    ("Marc Benioff", "CEO_OF", "Salesforce"),
    ("Salesforce", "ACQUIRED", "Slack"),
    ("Slack", "FOUNDED_BY", "Stewart Butterfield"),
    ("Slack", "FOUNDED_IN", "2013"),
]
